apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-storage-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: [FileSystemID/FileSystemAccessPointID]

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

